### Problem 76 counting summations


<p>It is possible to write five as a sum in exactly six different ways:</p>
<p style="margin-left:50px;">4 + 1<br />
3 + 2<br />
3 + 1 + 1<br />
2 + 2 + 1<br />
2 + 1 + 1 + 1<br />
1 + 1 + 1 + 1 + 1</p>
<p>How many different ways can one hundred be written as a sum of at least two positive integers?</p>


#### Solution 

This problem is similir to problem 31. We will use the same techniques.



In [4]:
## DYNAMIC PROGRAMMING
import numpy as np 
import itertools 
max_value = 100
coins_values = list(range(1,max_value))

coins_matrix = np.zeros((len(coins_values),max_value)).astype(int)
for j in range(max_value) :
    coins_matrix[0,j] = 1
for j in range(1,max_value) :
    target = j+1
    for i_x,x in enumerate(coins_values[1:]):
        i = i_x+1
        value = 0
        if x<target :
            value += sum([coins_matrix[ii,j-x] for ii in range(i+1)])
        elif x == target :
            value = 1
        else :
            break
        coins_matrix[i,j] = value

print(coins_matrix)        
print(coins_matrix[:,max_value-1].sum())
        


[[  1   1   1 ...   1   1   1]
 [  0   1   1 ...  49  49  50]
 [  0   0   1 ... 800 817 833]
 ...
 [  0   0   0 ...   1   2   3]
 [  0   0   0 ...   1   1   2]
 [  0   0   0 ...   0   1   1]]
190569291
